# Generated by Django 4.2.13 on 2024-05-23 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authUser.teacher'),
        ),
        migrations.AlterField(
            model_name='mycourses',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authUser.student'),
        ),
    ]
