# Generated by Django 4.2.13 on 2024-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_taught_by_alter_mycourses_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
