# Generated by Django 4.2.13 on 2024-05-23 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/Teachers')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=150)),
                ('shift', models.CharField(default='Day', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/students')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=2)),
                ('section', models.CharField(max_length=2)),
                ('contact_no', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=999)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/Staff')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=150)),
                ('shift', models.CharField(default='Day', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
